import AboutStyles from "../About/About.module.css";
import styles from "./PrivacyPolicy.module.css"
const PrivacyPolicy = () => {
   return (
      <div className={AboutStyles.ct + ` ${styles.ct}`}>
         <section>
            <h2>Privacy policy</h2>
            <p>
               This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use
               the Service and tells You about Your privacy rights and how the law protects You.
            </p>
            <p>
               We use Your Personal data to provide and improve the Service. By using the Service, You agree to the collection and use of
               information in accordance with this Privacy Policy.
            </p>
            <h3>Interpretation</h3>
            <p>
               The words of which the initial letter is capitalised have meanings defined under the following conditions. The following
               definitions shall have the same meaning regardless of whether they appear in singular or in plural.
            </p>
            <h3>Definitions</h3>
            <p>For the purposes of this Privacy Policy:</p>
            <ul>
               <li>
                  <b>Account</b> means a unique account created for You to access our Service or parts of our Service.
               </li>
               <li>
                  <b>Affiliate</b> means an entity that controls, is controlled by or is under common control with a party, where “control” means
                  ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other
                  managing authority.
               </li>
               <li>
                  <b>Company</b> (referred to as either “the Company”, “We”, “Us” or “Our” in this Agreement) refers to Agata Comunicación
                  Científica S.L., Calle Bajada del Caleruco, 26A, 4D – 39012, Santander, Spain.
               </li>
               <li>
                  <b>Cookies</b> are small files that are placed on Your computer, mobile device or any other device by a website, containing the
                  details of Your browsing history on that website among its many uses.
               </li>
               <li>
                  <b>Country</b> refers to: Spain
               </li>
               <li>
                  <b>Device</b> means any device that can access the Service such as a computer, a cellphone or a digital tablet.
               </li>
               <li>
                  <b>Personal Data</b> is any information that relates to an identified or identifiable individual. Service refers to the
                  Website.
               </li>
               <li>
                  <b>Service Provider</b> means any natural or legal person who processes the data on behalf of the Company. It refers to
                  third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the
                  Company, to perform services related to the Service or to assist the Company in analyzing how the Service is used.
               </li>
               <li>
                  <b>Usage Data</b> refers to data collected automatically, either generated by the use of the Service or from the Service
                  infrastructure itself (for example, the duration of a page visit).
               </li>
               <li>Website refers to Agata Communications, accessible from https://agata.agency/</li>
               <li>
                  <b>You</b> means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such
                  individual is accessing or using the Service, as applicable.
               </li>
            </ul>
            <h3>Links to Other Websites</h3>
            <p>
               Our Service may contain links to other websites that are not operated by Us. If You click on a third party link, You will be
               directed to that third party’s site. We strongly advise You to review the Privacy Policy of every site You visit.
            </p>
            <p>
               We have no control over and assume no responsibility for the content, privacy policies or practices of any third party sites or
               services.
            </p>
            <h3>Changes to this Privacy Policy</h3>
            <p>
               We may update Our Privacy Policy from time to time. We will notify You of any changes by posting the new Privacy Policy on this
               page.
            </p>
            <p>
               We will let You know via email and/or a prominent notice on Our Service, prior to the change becoming effective and update the
               “Last updated” date at the top of this Privacy Policy.
            </p>
            <p>
               You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they
               are posted on this page.
            </p>
            <h3>Contact Us</h3>
            <p> If you have any questions about this Privacy Policy, You can contact us by email.</p>
         </section>
      </div>
   );
};
export default PrivacyPolicy;
