on:
   push:
      branches:
         - main
name: Deploy website on push to Repo

jobs:
   deploy:
      name: Deploy
      runs-on: ubuntu-latest

      steps:
         - name: Get latest code
           uses: actions/checkout@v4

         - name: Use Node.js 16
           uses: actions/setup-node@v2
           with:
              node-version: "16"

         - name: Build frontend
           run: |
              cd /home/runner/work/ChatPec/ChatPec/frontend
              npm install  
              npm run build --mode production

         - name: Deploy frontend to cPanel
           uses: SamKirkland/FTP-Deploy-Action@4.3.0
           with:
              server: ${{ secrets.CPANEL_SERVER }}
              username: ${{ secrets.CPANEL_USERNAME }}
              password: ${{ secrets.CPANEL_PASSWORD }}
              local-dir: /home/runner/work/ChatPec/ChatPec/frontend/dist/
              server-dir: ./public_html/

         - name: Install backend dependencies
           run: |
              cd /home/runner/work/ChatPec/ChatPec/backend
              npm install

         - name: Deploy backend to cPanel
           uses: SamKirkland/FTP-Deploy-Action@4.3.0
           with:
              server: ${{ secrets.CPANEL_SERVER }}
              username: ${{ secrets.CPANEL_USERNAME }}
              password: ${{ secrets.CPANEL_PASSWORD }}
              local-dir: /home/runner/work/ChatPec/ChatPec/backend/
              server-dir: ./api/
