on:
   push:
      branches:
         - main
name: Deploy website ao se fazer push

jobs:
   deploy:
      name: Deploy
      runs-on: ubuntu-latest

      steps:
         - name: Get latest code
           uses: actions/checkout@v3

         - name: Use Node.js 16
           uses: actions/setup-node@v2
           with:
              node-version: "16"

         - name: Build project
           run: |
              npm install  
              npm run build

         - name: Deploy to cPanel
           uses: SamKirkland/FTP-Deploy-Action@4.3.4
           with:
              server: ${{ secrets.CPANEL_SERVER }}
              username: ${{ secrets.CPANEL_USERNAME }}
              password: ${{ secrets.CPANEL_PASSWORD }}
              local-dir: ./build/
